services:

  postgres:
    image: postgres
    restart: no
    container_name: postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestapp:
    build: .
    container_name: nestapp
    restart: no
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/db?schema=public

volumes:
  postgres_data:
